version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: mysql-srv

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
